# Define device-tree path
DEVICE_PATH := device/asus/ME173X

# Assert
TARGET_OTA_ASSERT_DEVICE := ME173X,ASUS_ME173X,asus_ME173X,lineage_ME173X

# Platform
TARGET_BOARD_PLATFORM := mt6589
TARGET_NO_FACTORYIMAGE := true
BOARD_VENDOR := Asus

# Architecture
ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_NEON := true
TARGET_SOC := mt6589
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true

# Block
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1611661312
BOARD_CACHEIMAGE_PARTITION_SIZE := 419430400
BOARD_FLASH_BLOCK_SIZE := 2048
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4830789632

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

# Kernel
TARGET_NO_KERNEL := true
BOARD_CUSTOM_BOOTIMG := true
BOARD_KERNEL_IMAGE_NAME := zImage

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/fstab.mt6589

# Display
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
PRESENT_TIME_OFFSET_FROM_VSYNC_NS := 0
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/egl.cfg

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := mt6589
TARGET_NO_BOOTLOADER := true

# Bluetooth
MTK_BT_SUPPORT := yes
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth

# Camera
USE_CAMERA_STUB := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
TARGET_NEEDS_LEGACY_CAMERA_HAL1_DYN_NATIVE_HANDLE := true
TARGET_USES_NON_TREBLE_CAMERA := true

# System properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Build pre-optimized to speed up initial boot
WITH_DEXPREOPT := true
WITH_DEXPREOPT_PIC := true

# Disable API check
WITHOUT_CHECK_API := true