# inherit from the proprietary version
-include vendor/Asus/ME173X/BoardConfigVendor.mk

# Architecture
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6589
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := ME173X

# Block
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1611661312
BOARD_CACHEIMAGE_PARTITION_SIZE := 419430400
BOARD_FLASH_BLOCK_SIZE := 2048
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4830789632
TARGET_USERIMAGES_USE_EXT4 := true

# fix this up by examining /proc/mtd on a running device
# BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
# BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
# BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
# BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
# BOARD_FLASH_BLOCK_SIZE := 131072

# Camera
USE_CAMERA_STUB := true

# Kernel
BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

TARGET_PREBUILT_KERNEL := device/Asus/ME173X/kernel

# Asserts
TARGET_OTA_ASSERT_DEVICE := cm_ME173X,ME173X,lineage_ME173X

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
